---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consumer
    spec:
      containers:
      - image: karlhopkinsonturrell/distributed-tracing-consumer
        name: distributed-tracing-consumer
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENV
            value: "test"
          - name: DD_SERVICE
            value: "consumer"
          - name: DD_VERSION
            value: "0.0.2"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_TRACE_SAMPLE_RATE
            value: "1"
        resources: {}
status: {}
